title: "Fatoumata Kamissoko"
description: Portfolio en bioinformatique – Analyse des données transcriptomiques et étude des réseaux de régulation génique dans le contexte du stress environnemental et de l’horloge circadienne
show_downloads: true
theme: jekyll-theme-cayman
lang: fr
author:
  name: "Fatoumata Kamissoko"
  email: "fkamissoko584@gmail.com"
social_links:
  linkedin: fatoumata-kamissoko-685706275
  github: Fatim1401
google_analytics: 
plugins:
  - jekyll-seo-tag
